name: "CDE Discovery Action"
description: "AI-powered discovery of CDEs matching user criteria"

inputs:
  timeout_minutes:
    description: "Timeout in minutes for execution"
    required: false
    default: "15"
  anthropic_api_key:
    description: "Anthropic API key"
    required: true
  cborg_api_key:
    description: "CBORG API key"
    required: true
  github_token:
    description: "GitHub token with repo and issues permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create CDE Discovery Prompt
      shell: bash
      run: ./.github/actions/cde-discovery-action/create-prompt.sh

    - name: Run Claude Code for CDE Discovery
      uses: ./.github/actions/claude-code-action
      with:
        prompt_file: /tmp/claude-prompts/cde-discovery-prompt.txt
        allowed_tools: "Grep,Read,LS,Glob"
        timeout_minutes: ${{ inputs.timeout_minutes }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        cborg_api_key: ${{ inputs.cborg_api_key }}
        github_token: ${{ inputs.github_token }}
        output_file: /tmp/claude-output.txt

    - name: Post CDE Discovery Results
      shell: bash
      run: ./.github/actions/cde-discovery-action/post-results.sh
      env:
        GH_TOKEN: ${{ inputs.github_token }}

