name: "CDE Discovery Action"
description: "AI-powered discovery of CDEs matching user criteria"

inputs:
  timeout_minutes:
    description: "Timeout in minutes for execution"
    required: false
    default: "15"
  anthropic_api_key:
    description: "Anthropic API key"
    required: true
  cborg_api_key:
    description: "CBORG API key"
    required: true
  github_token:
    description: "GitHub token with repo and issues permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create CDE Discovery Prompt
      shell: bash
      run: |
        mkdir -p /tmp/claude-prompts
        cat > /tmp/claude-prompts/cde-discovery-prompt.txt << EOF
        You are a CDE (Common Data Element) discovery assistant for biomedical research data harmonization.

        TASK: Analyze the GitHub issue request below and find relevant CDEs from the repository's data sources.

        ISSUE DETAILS:
        - Issue Number: ${{ github.event.issue.number }}
        - Title: ${{ github.event.issue.title }}
        - Body: ${{ github.event.issue.body }}
        - User: ${{ github.event.issue.user.login }}

        REPOSITORY CONTEXT:
        - This repo contains CDEs from multiple sources: PhenX-REDCap, NIH/NLM, CADSR, RADx-UP
        - Data locations:
          * data/phenx-redcap/all-redcap/ - PhenX CDEs in REDCap format
          * data/nlm/nlm-cdes.csv - NIH/NLM CDEs in CSV format  
          * data/cadsr/ - CADSR CDEs in JSON format
          * data/radx-up/ - RADx-UP data dictionary
        - LinkML schemas:
          * linkml/phenx_schema.yaml - Generated LinkML schema for PhenX CDEs
          * linkml/nih_nlm_schema.yaml - Generated LinkML schema for NIH/NLM CDEs
          * linkml/radx_up_schema.yaml - Generated LinkML schema for RADx-UP

        STEPS:
        1. The GitHub issue details are provided via environment variable. Parse the user's request for:
           - Clinical concepts/variables they need
           - Target population (adult/pediatric/both)
           - Preferred data sources
           - Any specific CDE IDs mentioned

        2. Search for relevant CDEs systematically:
           - Use Grep tool to search for keywords across data files
           - Use Read tool to examine specific CDE files when promising matches found
           - Search LinkML schemas for structured metadata
           - Be thorough - check all data sources

        3. For each relevant CDE found, extract:
           - CDE ID/identifier
           - Source (PhenX, NIH/NLM, CADSR, RADx-UP)
           - Title/name and description
           - Key question text and response options
           - Target population if specified
           - File location in repository

        4. Score each CDE for relevance (1-100) based on:
           - Exact concept match (100)
           - Close concept match (80-90)
           - Related concept (60-80)
           - Tangentially related (30-60)
           - Population match (adult vs pediatric)

        5. Format response as detailed markdown analysis including:
           - Summary of search criteria interpreted from issue
           - Top 5-10 most relevant CDEs with full details
           - For each CDE: ID, source, relevance score, rationale, file path, key variables
           - Suggestions for harmonization if multiple sources have similar CDEs
           - Recommended next steps for the human curator

        IMPORTANT GUIDELINES:
        - Be thorough in searching across ALL data sources
        - Provide specific file paths and line numbers when possible  
        - Include confidence scores and detailed reasoning for each match
        - Look for exact question text matches as well as conceptual similarities
        - Consider population-specific variations (adult vs pediatric versions)
        - Suggest potential harmonization opportunities between similar CDEs
        - Focus on practical utility for the researcher's stated needs

        EXAMPLE SEARCH PATTERNS:
        - For smoking: search "smok", "cigarette", "tobacco", "nicotine"
        - For mental health: search "depress", "anxiety", "mood", "mental"
        - For demographics: search "age", "gender", "race", "ethnicity"

        Remember: The goal is to help researchers find the most appropriate CDEs for their specific research needs while highlighting harmonization opportunities.
        EOF

    - name: Run Claude Code for CDE Discovery
      uses: ./.github/actions/claude-code-action
      with:
        prompt_file: /tmp/claude-prompts/cde-discovery-prompt.txt
        allowed_tools: "Grep,Read,LS,Glob"
        timeout_minutes: ${{ inputs.timeout_minutes }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        cborg_api_key: ${{ inputs.cborg_api_key }}
        github_token: ${{ inputs.github_token }}
        output_file: /tmp/claude-output.txt

    - name: Post CDE Discovery Results
      shell: bash
      run: |
        # Check if Claude output exists and post as comment using gh CLI
        if [ -f /tmp/claude-output.txt ]; then
          echo "Posting Claude's CDE discovery results to issue #${{ github.event.issue.number }}"
          
          # Create formatted comment
          cat > /tmp/issue-comment.md << 'EOF'
# 🤖 AI CDE Discovery Results

Claude AI has analyzed your CDE discovery request and found the following results:

---

EOF
          
          # Append Claude's analysis
          cat /tmp/claude-output.txt >> /tmp/issue-comment.md
          
          # Post comment using GitHub CLI
          gh issue comment ${{ github.event.issue.number }} --body-file /tmp/issue-comment.md
        else
          echo "Error: No Claude output found to post"
          exit 1
        fi
      env:
        GH_TOKEN: ${{ inputs.github_token }}

