name: 🗂️ SSSOM Mapping Request
description: Request AI to generate SSSOM mappings between CDEs
title: "[SSSOM-MAP] "
labels: ["sssom-mapping", "ai-curation"]
body:
  - type: markdown
    attributes:
      value: |
        ## AI-Generated SSSOM Mappings
        
        This template will trigger our AI system to generate SSSOM (Simple Standard for Sharing Ontological Mappings) mappings between CDEs.

  - type: dropdown
    id: mapping_type
    attributes:
      label: Mapping Type
      description: What type of mapping are you requesting?
      options:
        - "Specific CDE to CDE mapping"
        - "CDE to domain/concept mapping"
        - "Cross-source harmonization (find all related CDEs)"
        - "Validation of existing mapping"
      default: 0
    validations:
      required: true

  - type: textarea
    id: source_cde
    attributes:
      label: Source CDE(s)
      description: Specify the source CDE(s) you want to map FROM
      placeholder: |
        e.g.,
        - PX030604 (PhenX adult smoking status)
        - "Do you now smoke cigarettes?" (NIH/NLM)
        - Multiple CDEs: PX030603, PX030604, PX030701
    validations:
      required: true

  - type: textarea
    id: target_cde
    attributes:
      label: Target CDE(s) or Domain
      description: Specify target CDE(s) to map TO, or leave blank for domain-wide search
      placeholder: |
        e.g.,
        - Specific: "Do_you_now_smoke_cigarettes?" (RADx-UP)
        - Domain: "All smoking-related CDEs in NIH/NLM"
        - Leave blank to find all potential mappings

  - type: checkboxes
    id: source_systems
    attributes:
      label: Source Systems to Include
      description: Which CDE sources should be included in the mapping analysis?
      options:
        - label: "PhenX-REDCap"
        - label: "NIH/NLM"
        - label: "CADSR"
        - label: "RADx-UP"

  - type: dropdown
    id: mapping_precision
    attributes:
      label: Mapping Precision
      description: How strict should the mapping criteria be?
      options:
        - "Exact matches only (very high confidence)"
        - "Close matches (high confidence)"
        - "Related matches (medium confidence)"
        - "Broad matches (include loosely related)"
      default: 1

  - type: textarea
    id: mapping_criteria
    attributes:
      label: Specific Mapping Criteria
      description: Any specific criteria or constraints for the mappings?
      placeholder: |
        e.g.,
        - Must have compatible response scales
        - Same target population (adult vs pediatric)
        - Similar measurement precision
        - Compatible with longitudinal studies

  - type: checkboxes
    id: mapping_analysis
    attributes:
      label: Analysis Focus
      description: What aspects should the AI analyze when creating mappings?
      options:
        - label: "Question text similarity"
        - label: "Response option compatibility"
        - label: "Population target alignment"
        - label: "Clinical concept equivalence"
        - label: "Measurement scale comparability"
        - label: "Temporal aspects (current vs historical)"

  - type: textarea
    id: use_case
    attributes:
      label: Use Case Context
      description: How will these mappings be used?
      placeholder: |
        e.g.,
        - Data harmonization across multiple studies
        - Converting between data collection platforms
        - Meta-analysis preparation

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other information that would help generate better mappings?
      placeholder: |
        e.g.,
        - Known issues with certain CDEs
        - Previous mapping attempts
        - Specific regulatory requirements