name: "SSSOM Mapping Action"
description: "Generate SSSOM mappings between CDEs using AI analysis"

inputs:
  timeout_minutes:
    description: "Timeout in minutes for execution"
    required: false
    default: "20"
  anthropic_api_key:
    description: "Anthropic API key"
    required: true
  cborg_api_key:
    description: "CBORG API key"
    required: true
  github_token:
    description: "GitHub token with repo and issues permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create SSSOM Mapping Prompt
      shell: bash
      run: ./.github/actions/sssom-mapping-action/create-prompt.sh
      env:
        ISSUE_NUMBER: ${{ github.event.issue.number }}

    - name: Run Claude Code for SSSOM Mapping
      uses: ./.github/actions/claude-code-action
      with:
        prompt_file: /tmp/claude-prompts/sssom-mapping-prompt.txt
        allowed_tools: "Read,Write,Grep,LS,Glob"
        timeout_minutes: ${{ inputs.timeout_minutes }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        cborg_api_key: ${{ inputs.cborg_api_key }}
        github_token: ${{ inputs.github_token }}